name: Create preview environment

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  # The preview script can't handle concurrent deploys
  group: codepreview
  cancel-in-progress: false

# TODO: Define minimal permissions, I haven't found which one is necessary to allow writing comments on commits
# see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
#permissions:
#  contents: read # for checkout

jobs:
  preview:

    runs-on: ubuntu-latest

    steps:
      - name: Install ansible
        run: python3 -m pip install --user ansible

      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main

      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.1
        with:
          java-version: 'adopt:1.11.0-11'
          node-version: '16.7.0'

      - name: Prepare db seed
        run: cp 02-persistence-postgres-skunk/docker/seed.sql seed.sql

      - name: Compile
        run: sbt compile

      - name: Package app
        run: sbt main-http-http4s-postgres-skunk/universal:packageBin && mv 03-main-http-http4s-postgres-skunk/target/universal/main-http-http4s-postgres-skunk-0.1.0-SNAPSHOT.zip server.zip

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$CODEPREVIEW_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking=no" > ~/.ssh/config
        shell: bash
        env:
          CODEPREVIEW_PRIVATE_KEY: ${{ secrets.CODEPREVIEW_PRIVATE_KEY }}

      - name: Create codepreview scripts
        run: |
          rm -rf ./infra
          curl -u "github:$CODEPREVIEW_TOKEN" -O https://devinsideyou.codepreview.io/devinsideyou.zip
          unzip devinsideyou.zip -d .
          chmod +x ./infra/scripts/*.sh
        shell: bash
        env:
          CODEPREVIEW_TOKEN: ${{ secrets.CODEPREVIEW_TOKEN }}

      - name: Create preview env
        run: cd infra && ./scripts/deploy-preview.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}

